version: '3.6'
services:
  web-monitor:
    image: ghcr.io/iceoid/website-monitoring-docker
    container_name: web-monitor
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - EMAIL_ADDRESS=$EMAIL_ADDRESS
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      # URLS are delimited by a comma i.e a.com,b.net,https://c.io
      - URLS=$URLS
    volumes:
      - type: bind
        source: ./scripts/custom-cron
        target: /etc/cron.d/
